const newObj = new Object();
console.log('value of newObj', newObj);
console.log('typeof newObj', newObj);
const newArray = new Array();
console.log('value of newArray', newArray);
console.log('typeof newArray', newArray);
const newString = new String();
console.log('value of newString', newString);
console.log('typeof newString', newString);
const newFunct = new Function();
console.log('value of newFunct', newFunct);
console.log('typeof newFunct', newFunct);
const newNumb = new Number();
console.log('value of newNumb', newNumb);
console.log('typeof newNumb', newNumb);
const newBoolean = new Boolean();
console.log('value of newBoolean', newBoolean);
console.log('typeof newBoolean', newBoolean);
